name:                glossy-haskell-game
version:             0.1.0.0
github:              "bergsans/glossy-haskell-game"
license:             BSD3
author:              "Claes-Magnus Berg"
maintainer:          "bergclaesmagnus@gmail.com"
copyright:           "MIT"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            playing-with-haskell

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/bergsans/glossy-haskell-game#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  glossy-haskell-game-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - glossy-haskell-game

tests:
  glossy-haskell-game-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - glossy-haskell-game
